name: ci prod
"on":
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: self-hosted
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - name: clean previous version
        run: rm -rf $(echo ${{secrets.WEB_PATH}} | base64 --decode)
      - name: deploy new version
        run: cp -R ./build/web/ $(echo ${{secrets.WEB_PATH}} | base64 --decode)
